import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { dirname, resolve } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const sqlWasmPlugin = {
	name: "sql-wasm-copy",
	setup(build) {
		build.onEnd(() => {
			const src = resolve("node_modules/sql.js/dist/sql-wasm.wasm");
			const dest = resolve("sql-wasm.wasm");
			if (existsSync(src)) {
				copyFileSync(src, dest);
			}
		});
	},
};

const shared = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	treeShaking: true,
	plugins: [sqlWasmPlugin],
};

if (prod) {
	await esbuild.build({
		...shared,
		outfile: "main.js",
		minify: true,
		sourcemap: false,
	});
	process.exit(0);
} else {
	const context = await esbuild.context({
		...shared,
		outfile: "main.js",
		sourcemap: "inline",
	});
	await context.watch();
}
